services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    volumes:
      - grafana_data:/var/lib/grafana

  backend:
    build: ./backend
    depends_on:
      - db
      - logger-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: 3000
      LOKI_HOST: http://loki:3100
      LOGGER_SERVICE_URL: http://logger-service:4000/log
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  auth-service:
    build: ./auth-service
    depends_on:
      - db
      - logger-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: 3002
      LOKI_HOST: http://loki:3100
      LOGGER_SERVICE_URL: http://logger-service:4000/log
    ports:
      - "3002:3002"
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  logger-service:
    build: ./logger-service
    ports:
      - "4000:4000"
    environment:
      - LOKI_HOST=http://loki:3100
    depends_on:
      - loki

volumes:
  db_data:
  loki_data:
  grafana_data:
