global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
  - job_name: 'logger-service'
    static_configs:
      - targets: ['logger-service:4000']
